# Banco de dados postgres para uso pelo keycloak
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
type: Opaque
data:
  # PostgreSQL credentials
  postgres-user: cG9zdGdyZXM=            # base64 encoded "postgres"
  postgres-password: cG9zdGdyZXM=        # base64 encoded "postgres"
  postgres-db: a2V5Y2xvYWs=              # base64 encoded "keycloak"