apiVersion: apps/v1
kind: Deployment
metadata:
  name: filecutgestao
  labels:
    app: filecutgestao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filecutgestao
  template:
    metadata:
      labels:
        app: filecutgestao
    spec:
      containers:
        - name: filecutgestao-container
          image: ghcr.io/grupo-68-fiap/fiapfilecut/gestao:latest
          env:
            - name: RABBITMQ_CONNECTION_STRING
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-credentials
                  key: RABBITMQ_CONNECTION_STRING
            - name: OPENID_AUTHORITY
              valueFrom:
                secretKeyRef:
                  name: cognito-secrets
                  key: OPENID_AUTHORITY
            - name: OPENID_AUDIENCE
              valueFrom:
                secretKeyRef:
                  name: cognito-secrets
                  key: OPENID_AUDIENCE
            - name: OPENID_SECRET
              valueFrom:
                secretKeyRef:
                  name: cognito-secrets
                  key: OPENID_SECRET
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-storage-bucket
                  key: s3_access_key
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: s3-storage-bucket
                  key: s3_secret_key
            - name: S3_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: s3-storage-bucket
                  key: s3_bucket_name
            - name: S3_REGION
              valueFrom:
                secretKeyRef:
                  name: s3-storage-bucket
                  key: s3_region      
          envFrom:
            - configMapRef:
                name: filecutgestao-configmap
          ports:
            - containerPort: 8080
              name: http
          livenessProbe:
            httpGet:
              path: /swagger
              port: 8080
            periodSeconds: 10
            failureThreshold: 3
            initialDelaySeconds: 30
          readinessProbe:
            httpGet:
              path: /swagger
              port: 8080
            periodSeconds: 10
            failureThreshold: 5
            initialDelaySeconds: 30
          resources:
            requests:
              memory: 64Mi
              cpu: 5m
            limits:
              memory: 256Mi
              cpu: 200m