apiVersion: v1 # Service da API do tipo LoadBalancer
kind: Service
metadata:
  labels:
      app: filecutgestao-svc
  name: filecutgestao-svc
spec:
  type: LoadBalancer
  selector:
    app: filecutgestao
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP