apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3.9-management  # RabbitMQ image with management plugin
        ports:
        - containerPort: 5672  # AMQP port
          name: amqp
        - containerPort: 15672  # Management UI port
          name: management
        env:
        - name: RABBITMQ_DEFAULT_USER  # Default username
          value: "admin"
        - name: RABBITMQ_DEFAULT_PASS  # Default password
          value: "password"
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1"
        livenessProbe:
          tcpSocket:
            port: 5672  # AMQP port for liveness check
          initialDelaySeconds: 60  # Wait 60 seconds before starting probes
          periodSeconds: 30  # Check every 30 seconds
        readinessProbe:
          tcpSocket:
            port: 5672  # AMQP port for readiness check
          initialDelaySeconds: 20  # Wait 20 seconds before starting probes
          periodSeconds: 10  # Check every 10 seconds