# Secret
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
type: Opaque
data:
  username: YWRtaW4=  # base64 encoded "admin"
  password: YWRtaW4=  # base64 encoded "admin"
  RABBITMQ_CONNECTION_STRING: YW1xcDovL2FkbWluOmFkbWluQHJhYmJpdG1xOjU2NzI=