# Secret
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
type: Opaque
data:
  username: YWRtaW4=  # base64 encoded "admin"
  password: cGFzc3dvcmQ=  # base64 encoded "password"
  RABBITMQ_CONNECTION_STRING: YW1xcDovL2FkbWluOnBhc3N3b3JkQHJhYmJpdG1xOjU2NzI=